FROM dunglas/frankenphp:php8.3-bookworm AS builder

RUN apt-get update && \
  apt-get install curl wget gpg --no-install-recommends -y && \
  cd /tmp && mkdir extract && \
  wget --progress=dot:giga -O atatus.tar.gz https://s3.amazonaws.com/atatus-artifacts/atatus-php/downloads/atatus-php-1.17.0-x64-debian.tar.gz -O atatus.tar.gz && \
  tar -xzf atatus.tar.gz -C extract --strip-components=1 && \
  mkdir /etc/atatus && mkdir /etc/frankenphp/php.d

FROM dunglas/frankenphp:php8.3-bookworm

ARG USER=nhsla
ARG UID=1000
ARG GID=1000
ENV XDG_CONFIG_HOME=/nhsla/config
ENV XDG_DATA_HOME=/nhsla/data

COPY --from=builder /tmp/extract/usr/bin/atatus-php-collector /usr/bin/atatus-php-collector
COPY --from=builder /tmp/extract/usr/lib/atatus-php/x86_64/atatus_php_zts_8.3.so /tmp/atatus.so
COPY rootfs /

RUN mkdir /etc/atatus && \
  mkdir /etc/frankenphp/php.d && \
  mkdir -p /usr/lib/frankenphp/modules && \
  mkdir -p /nhsla/logs/atatus && mkdir -p /nhsla/run && mkdir -p /nhsla/data/caddy && \
  EXT_DIR=$(php-config --extension-dir) && \
  cp /tmp/atatus.so "$EXT_DIR/atatus.so" && \
  rm /tmp/atatus.so && \
  install-php-extensions \
    apcu \
    curl \
    xml \
     gd \
    mbstring \
    soap \
    zip \ 
    ldap \
    bcmath \
    tidy \
    opcache \
    imagick \
    sqlite3 \
    intl \
    redis \
    pgsql && \
  groupadd -g ${GID} -r ${USER} && \
  useradd -l -u ${UID} -r -g ${USER} -d /home/nhsla -s /bin/bash nhsla && \
  chown -R ${USER}:${USER} /etc/atatus /nhsla

COPY --chown=${UID}:${UID} index.php /app/index.php
COPY --chown=${UID}:${UID} index-broken.php /app/index-broken.php

USER ${UID}
HEALTHCHECK CMD curl -f http://localhost:2019/metrics || exit 1
ENTRYPOINT ["/usr/local/bin/frankenphp", "run"]
CMD ["--config", "/etc/frankenphp/Caddyfile", "--adapter", "caddyfile"]